name: input-secrets-example

on:
  workflow_dispatch:
    inputs:
      numberPublic:
        type: string
        required: true
        description: Public number
      numberPrivate:
        type: string
        required: true
        description: Private number

env:
  NUMBER_PUBLIC: ${{ inputs.numberPublic }}

jobs:
  lab:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print the numbers
        run: |
          NUMBER_PRIVATE=$(jq -r '.inputs.numberPrivate' $GITHUB_EVENT_PATH)
          echo ::add-mask::$NUMBER_PRIVATE

          echo "The public number is $NUMBER_PUBLIC"
          echo "The private number is $NUMBER_PRIVATE"
          SUM=$(($NUMBER_PUBLIC + $NUMBER_PRIVATE))
          echo "The sum of the public and private numbers is $SUM"
